/*
- Create all the Raw/Source Tables in the data-raw dataset
- These are not created via Dbt, I'm imagining that these tables are created by their respective source systems & BU's
*/

-- S_COUNTRY Table DDL
CREATE OR REPLACE TABLE source.RW_COUNTRY (
    COUNTRY_CODE STRING NOT NULL,
    COUNTRY_NAME STRING,
    CREATE_TS TIMESTAMP,
    LAST_UPDT_TS TIMESTAMP,
    PRIMARY KEY (COUNTRY_CODE) NOT ENFORCED
);

-- S_MARKET Table DDL
CREATE OR REPLACE TABLE source.RW_MARKET (
    MARKET_CODE STRING NOT NULL,
    MARKET_NAME STRING,
    CREATE_TS TIMESTAMP,
    LAST_UPDT_TS TIMESTAMP,
    PRIMARY KEY (MARKET_CODE) NOT ENFORCED
);
-- S_SUPPLIER Table DDL
CREATE OR REPLACE TABLE source.RW_SUPPLIER (
    SUPPLIER_ID STRING NOT NULL,
    SUPPLIER_NAME STRING,
    SUPPLIER_DESC STRING,
    MARKET_CODE STRING,
    COUNTRY_CODE STRING,
    CREATE_TS TIMESTAMP,
    LAST_UPDT_TS TIMESTAMP,
    PRIMARY KEY (SUPPLIER_ID) NOT ENFORCED,
    FOREIGN KEY (MARKET_CODE) REFERENCES source.RW_MARKET(MARKET_CODE) NOT ENFORCED,
    FOREIGN KEY (COUNTRY_CODE) REFERENCES source.RW_COUNTRY(COUNTRY_CODE) NOT ENFORCED
);

-- S_BUYER Table DDL
CREATE OR REPLACE TABLE source.RW_BUYER (
    BUYER_ID STRING NOT NULL,
    BUYER_NAME STRING,
    BUYER_DESC STRING,
    MARKET_CODE STRING,
    COUNTRY_CODE STRING,
    CREATE_TS TIMESTAMP,
    LAST_UPDT_TS TIMESTAMP,
    PRIMARY KEY (BUYER_ID) NOT ENFORCED,
    FOREIGN KEY (COUNTRY_CODE) REFERENCES source.RW_COUNTRY(COUNTRY_CODE) NOT ENFORCED
);

-- S_PART Table DDL
CREATE OR REPLACE TABLE source.RW_PART (
    PART_ID STRING NOT NULL,
    PART_NAME STRING,
    PART_DESC STRING,
    SUPPLIER_ID STRING,
    COUNTRY_CODE STRING,
    CREATE_TS TIMESTAMP,
    LAST_UPDT_TS TIMESTAMP,
    PRIMARY KEY (PART_ID) NOT ENFORCED,
    FOREIGN KEY (SUPPLIER_ID) REFERENCES source.RW_SUPPLIER(SUPPLIER_ID) NOT ENFORCED,
    FOREIGN KEY (COUNTRY_CODE) REFERENCES source.RW_COUNTRY(COUNTRY_CODE) NOT ENFORCED
);

-- S_ORDER Table DDL
CREATE OR REPLACE TABLE source.RW_ORDER (
    ORDER_ID STRING NOT NULL,
    PART_ID STRING,
    PART_NAME STRING,
    PURCHASED_QTY INTEGER,
    UNIT_COST_PRICE NUMERIC,
    SUPPLIER_ID STRING,
    CREATE_TS TIMESTAMP,
    LAST_UPDT_TS TIMESTAMP,
    PRIMARY KEY (ORDER_ID) NOT ENFORCED,
    FOREIGN KEY (PART_ID) REFERENCES source.RW_PART(PART_ID) NOT ENFORCED,
    FOREIGN KEY (SUPPLIER_ID) REFERENCES source.RW_SUPPLIER(SUPPLIER_ID) NOT ENFORCED
);

-- S_SALE Table DDL
CREATE OR REPLACE TABLE source.RW_SALE (
    SALE_ID STRING NOT NULL,
    PART_ID STRING,
    PART_NAME STRING,
    SOLD_QTY INTEGER,
    UNIT_SELL_PRICE NUMERIC,
    BUYER_ID STRING,
    CREATE_TS TIMESTAMP,
    LAST_UPDT_TS TIMESTAMP,
    PRIMARY KEY (SALE_ID) NOT ENFORCED,
    FOREIGN KEY (PART_ID) REFERENCES source.RW_PART(PART_ID) NOT ENFORCED,
    FOREIGN KEY (BUYER_ID) REFERENCES source.RW_BUYER(BUYER_ID) NOT ENFORCED
);

